---
development:
  cloud_name: dtwhem3ku
  api_key: '293459784826278'
  api_secret: vWTAnom6dQ_v32bpJby1aBVGuLc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dtwhem3ku
  api_key: '293459784826278'
  api_secret: vWTAnom6dQ_v32bpJby1aBVGuLc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dtwhem3ku
  api_key: '293459784826278'
  api_secret: vWTAnom6dQ_v32bpJby1aBVGuLc
  enhance_image_tag: true
  static_image_support: false

